# .github/workflows/render-ci.yml
name: Schedulify Production Deployment on Render
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - merged
  
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Test
        run: |
          pnpm install
          npm run test

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
